name: product_list
definition:
  # Wires connect to data in collections
  wires:
    product:
      collection: usio/shop.product
      fields:
        usio/shop.name:
        usio/shop.description:
        usio/shop.price:
        usio/shop.image:
        usio/shop.initials:
        usio/shop.slug:
        usio/shop.published:
      batchsize: 200
      order:
        - desc: true
          field: uesio/core.updatedat
  # Components determine the layout and composition of your view
  components:
    - uesio/io.viewlayout:
        left:
          - usio/shop.nav:
        content:
          - uesio/appkit.form_list:
              wire: product
              avataricon: sell
              linkedComponentType: uesio/io.table
              linkedComponentId: productTable
              filters:
                - uesio/io.searchbox:
                    uesio.variant: uesio/appkit.main
                    wire: product
                    placeholder: Search Products
                    searchFields:
                      - usio/shop.name
                      - usio/shop.description
              content:
                - uesio/io.table:
                    uesio.variant: uesio/appkit.main
                    selectable: true
                    rowactions:
                      - icon: visibility
                        text: View
                        type: DEFAULT
                        uesio.display:
                          - type: recordIsNotNew
                        signals:
                          - signal: route/NAVIGATE_TO_ASSIGNMENT
                            viewtype: detail
                            recordid: ${uesio/core.id}
                            collection: usio/shop.product
                    columns:
                      - components:
                          - uesio/io.avatar:
                              uesio.variant: uesio/appkit.tablecolumn
                              text: ${initials}
                              image: $UserFile{usio/shop.image}
                        uesio.display:
                          - type: fieldMode
                            mode: EDIT
                      - components:
                          - usio/shop.product_tile:
                        uesio.display:
                          - type: fieldMode
                            mode: READ
                      - field: usio/shop.name
                        uesio.display:
                          - type: fieldMode
                            mode: EDIT
                      - field: usio/shop.description
                        uesio.display:
                          - type: fieldMode
                            mode: EDIT
                      - field: usio/shop.price
                      - field: usio/shop.slug
                      - field: usio/shop.published
                    uesio.id: productTable
                    wire: product
                    pagesize: 10
