name: product_pay
definition:
  wires:
    product:
      collection: usio/pay.product
      fields:
        usio/pay.name:
        usio/pay.description:
        usio/pay.image:
        usio/pay.price:
        usio/pay.initials:
        usio/pay.slug:
        usio/pay.published:
        uesio/core.updatedby: {}
        uesio/core.updatedat: {}
        uesio/core.createdby: {}
        uesio/core.createdat: {}
        uesio/core.owner: {}
      conditions:
        - field: usio/pay.slug
          valueSource: PARAM
          param: slug
  components:
    - uesio/io.item:
        wire: product
        components:
          - usio/pay.pay_screen:
              amount: ${price}
              secondaryAmount: 1.99
              description: ${name}
              onSubmitSignals:
                - signal: bot/CALL
                  bot: usio/pay.buy_product
                  stepId: "submit_token"
                  params:
                    token: "$Text{$SignalOutput{[checkout][token]}}"
                    firstName: "$Text{$SignalOutput{[checkout][firstName]}}"
                    lastName: "$Text{$SignalOutput{[checkout][lastName]}}"
                    address: "$Text{$SignalOutput{[checkout][address]}}"
                    city: "$Text{$SignalOutput{[checkout][city]}}"
                    state: "$Text{$SignalOutput{[checkout][state]}}"
                    zip: "$Text{$SignalOutput{[checkout][zip]}}"
                    product: ${uesio/core.id}
              main:
                - uesio/io.box:
                    uesio.styleTokens:
                      root:
                        - bg-white
                        - flex
                        - p-4
                        - rounded
                        - gap-4
                        - mx-4
                        - my-8
                    components:
                      - uesio/io.image:
                          src: $UserFile{image}
                          height: 280
                      - uesio/io.box:
                          uesio.styleTokens:
                            root:
                              - grid
                              - grid-rows-[min-content_1fr]
                              - max-w-[250px]
                          components:
                            - uesio/io.titlebar:
                                uesio.variant: usio/pay.item
                                title: ${name}
                                subtitle: ${description}
                            - uesio/io.grid:
                                uesio.variant: uesio/io.center
                                items:
                                  - uesio/io.text:
                                      uesio.styleTokens:
                                        root:
                                          - text-3xl
                                          - text-indigo-500
                                          - font-bold
                                      text: $Currency{price}
  params:
    slug:
      type: TEXT
      required: true
