name: product_list
definition:
  # Wires connect to data in collections
  wires:
    product:
      collection: usio/pay.product
      fields:
        usio/pay.name:
        usio/pay.description:
        usio/pay.price:
        usio/pay.image:
        usio/pay.initials:
        usio/pay.slug:
        usio/pay.published:
      batchsize: 200
      order:
        - desc: true
          field: uesio/core.updatedat
  # Components determine the layout and composition of your view
  components:
    - uesio/io.viewlayout:
        left:
          - usio/pay.nav:
        content:
          - uesio/io.titlebar:
              title: $Collection{product:pluralLabel}
              subtitle: List View
              uesio.variant: usio/pay.main
              avatar:
                - uesio/io.text:
                    uesio.variant: uesio/io.icon
                    text: sell
              actions:
                - uesio/io.toolbar:
                    linkedComponentType: uesio/io.table
                    linkedComponentId: productTable
                    right:
                      - uesio/io.button:
                          signals:
                            - signal: wire/SAVE
                              wires:
                                - product
                            - signal: component/CALL
                              component: uesio/io.table
                              componentsignal: SET_READ_MODE
                              targettype: specific
                              componentid: productTable
                            - signal: component/CALL
                              component: uesio/io.table
                              componentsignal: CLEAR_SELECTED
                              targettype: specific
                              componentid: productTable
                          text: $Label{uesio/io.save}
                          hotkey: "meta+s"
                          uesio.variant: usio/pay.primary
                          uesio.display:
                            - type: wireHasChanges
                              wire: product
                      - uesio/io.button:
                          signals:
                            - signal: wire/CANCEL
                              wire: product
                            - signal: component/CALL
                              component: uesio/io.table
                              componentsignal: SET_READ_MODE
                              targettype: specific
                              componentid: productTable
                            - signal: component/CALL
                              component: uesio/io.table
                              componentsignal: CLEAR_SELECTED
                              targettype: specific
                              componentid: productTable
                          uesio.display:
                            - type: wireHasChanges
                              wire: product
                          text: $Label{uesio/io.cancel}
                          uesio.variant: usio/pay.secondary
                      - uesio/io.button:
                          signals:
                            - signal: component/CALL
                              component: uesio/io.table
                              componentsignal: TOGGLE_MODE
                              targettype: specific
                              componentid: productTable
                          uesio.display:
                            - type: mergeValue
                              value: EDIT
                              operator: NOT_EQUALS
                              sourceValue: $ComponentState{[uesio/io.table][productTable][mode]}
                            - type: wireHasNoChanges
                              wire: product
                          text: Edit
                          icon: edit_square
                          iconFill: false
                          uesio.variant: usio/pay.secondary
                      - uesio/io.button:
                          signals:
                            - signal: component/CALL
                              component: uesio/io.table
                              componentsignal: TOGGLE_MODE
                              targettype: specific
                              componentid: productTable
                          uesio.display:
                            - type: mergeValue
                              value: EDIT
                              operator: EQUALS
                              sourceValue: $ComponentState{[uesio/io.table][productTable][mode]}
                            - type: wireHasNoChanges
                              wire: product
                          icon: task_alt
                          iconFill: false
                          text: Read
                          uesio.variant: usio/pay.secondary
          - uesio/io.box:
              uesio.variant: usio/pay.primarysection
              components:
                - uesio/io.toolbar:
                    linkedComponentType: uesio/io.table
                    linkedComponentId: productTable
                    left:
                      - uesio/io.searchbox:
                          uesio.variant: usio/pay.main
                          wire: product
                          placeholder: Search Products
                          searchFields:
                            - usio/pay.name
                            - usio/pay.description
                    right:
                      - uesio/io.button:
                          text: Quick Create
                          icon: add_circle
                          uesio.variant: usio/pay.add
                          signals:
                            - signal: wire/CREATE_RECORD
                              wire: product
                              prepend: true
                          uesio.display:
                            - type: mergeValue
                              sourceValue: $ComponentState{[uesio/io.table][productTable][mode]}
                              value: EDIT
                      - uesio/io.button:
                          text: Delete
                          icon: delete
                          uesio.variant: usio/pay.delete
                          signals:
                            - signal: component/CALL
                              component: uesio/io.table
                              componentsignal: GET_SELECTED
                              targettype: specific
                              componentid: productTable
                            - signal: wire/TOGGLE_DELETE_STATUS
                          uesio.display:
                            - type: hasValue
                              value: $ComponentState{[uesio/io.table][productTable][selected->count]}
                - uesio/io.table:
                    uesio.variant: usio/pay.main
                    selectable: true
                    rowactions:
                      - icon: visibility
                        text: View
                        type: DEFAULT
                        uesio.display:
                          - type: recordIsNotNew
                        signals:
                          - signal: route/NAVIGATE_TO_ASSIGNMENT
                            viewtype: detail
                            recordid: ${uesio/core.id}
                            collection: usio/pay.product
                    columns:
                      - components:
                          - uesio/io.avatar:
                              uesio.variant: usio/pay.tablecolumn
                              text: ${initials}
                              image: $UserFile{usio/pay.image}
                        uesio.display:
                          - type: fieldMode
                            mode: EDIT
                      - components:
                          - usio/pay.product_tile:
                        uesio.display:
                          - type: fieldMode
                            mode: READ
                      - field: usio/pay.name
                        uesio.display:
                          - type: fieldMode
                            mode: EDIT
                      - field: usio/pay.description
                        uesio.display:
                          - type: fieldMode
                            mode: EDIT
                      - field: usio/pay.price
                      - field: usio/pay.slug
                      - field: usio/pay.published
                    uesio.id: productTable
                    mode: READ
                    wire: product
                    pagesize: 10
