name: product_detail_content
definition:
  # Wires connect to data in collections
  wires:
    product:
      collection: usio/shop.product
      fields:
        usio/shop.name:
        usio/shop.description:
        usio/shop.image:
        usio/shop.price:
        usio/shop.initials:
        usio/shop.slug:
        usio/shop.published:
        uesio/core.updatedby: {}
        uesio/core.updatedat: {}
        uesio/core.createdby: {}
        uesio/core.createdat: {}
        uesio/core.owner: {}
      conditions:
        - field: uesio/core.id
          valueSource: PARAM
          param: recordid
  # Components determine the layout and composition of your view
  components:
    - uesio/io.box:
        uesio.display:
          - type: paramIsSet
            param: recordid
        components:
          - uesio/appkit.detail_split:
              main:
                - uesio/io.list:
                    wire: product
                    uesio.id: productList
                    components:
                      - uesio/io.titlebar:
                          title: ${usio/shop.name}
                          subtitle: $Collection{label}
                          uesio.variant: uesio/appkit.main
                          actions:
                            - uesio/io.toolbar:
                                right:
                                  - uesio/io.button:
                                      signals:
                                        - signal: route/NAVIGATE
                                          path: buy/${slug}
                                      text: View Listing
                                      icon: visibility
                                      iconFill: false
                                      uesio.variant: uesio/appkit.secondary
                                      uesio.display:
                                        - type: mergeValue
                                          value: EDIT
                                          operator: NOT_EQUALS
                                          sourceValue: $ComponentState{[uesio/io.list][productList][mode]}
                                        - type: wireHasNoChanges
                                          wire: product
                                  - uesio/io.button:
                                      signals:
                                        - signal: wire/SAVE
                                          wires:
                                            - product
                                        - signal: component/CALL
                                          component: uesio/io.list
                                          componentsignal: SET_READ_MODE
                                          targettype: specific
                                          componentid: productList
                                      text: Save
                                      hotkey: "meta+s"
                                      uesio.variant: uesio/appkit.primary
                                      uesio.display:
                                        - type: group
                                          conjunction: OR
                                          conditions:
                                            - type: wireHasChanges
                                              operator: EQUALS
                                              wire: product
                                  - uesio/io.button:
                                      signals:
                                        - signal: wire/CANCEL
                                          wire: product
                                      text: Cancel
                                      uesio.variant: uesio/appkit.secondary
                                      uesio.display:
                                        - type: wireHasChanges
                                          operator: EQUALS
                                          wire: product
                                  - uesio/io.button:
                                      signals:
                                        - signal: component/CALL
                                          component: uesio/io.list
                                          componentsignal: TOGGLE_MODE
                                          targettype: specific
                                          componentid: productList
                                      text: Edit
                                      icon: edit_square
                                      iconFill: false
                                      uesio.variant: uesio/appkit.secondary
                                      uesio.display:
                                        - type: mergeValue
                                          value: EDIT
                                          operator: NOT_EQUALS
                                          sourceValue: $ComponentState{[uesio/io.list][productList][mode]}
                                        - type: wireHasNoChanges
                                          wire: product
                                  - uesio/io.button:
                                      signals:
                                        - signal: component/CALL
                                          component: uesio/io.list
                                          componentsignal: TOGGLE_MODE
                                          targettype: specific
                                          componentid: productList
                                      uesio.display:
                                        - type: mergeValue
                                          value: EDIT
                                          operator: EQUALS
                                          sourceValue: $ComponentState{[uesio/io.list][productList][mode]}
                                        - type: wireHasNoChanges
                                          wire: product
                                      icon: task_alt
                                      iconFill: false
                                      text: Read
                                      uesio.variant: uesio/appkit.secondary
                          avatar:
                            - uesio/io.menu:
                                uesio.variant: uesio/appkit.upload
                                arrow: true
                                closeButton: true
                                trigger:
                                  - uesio/io.avatar:
                                      uesio.variant: uesio/appkit.main
                                      text: ${initials}
                                      image: $UserFile{usio/shop.image}
                                content:
                                  - uesio/io.box:
                                      components:
                                        - uesio/io.titlebar:
                                            uesio.variant: uesio/appkit.sub
                                            title: Upload or Delete Product Image
                                        - uesio/io.field:
                                            labelPosition: none
                                            uesio.context:
                                              fieldMode: EDIT
                                            fieldId: usio/shop.image
                                            displayAs: IMAGE
                      - usio/shop.product_primary_section:
                      - uesio/appkit.audit_info_section:
                      - uesio/appkit.delete_section:
              left:
                - uesio/io.tabs:
                    uesio.variant: uesio/appkit.main
                    tabs:
                      - id: orders
                        label: Orders
                        components:
    - uesio/io.box:
        uesio.variant: uesio/io.section
        uesio.display:
          - type: paramIsNotSet
            param: recordid
        components:
          - uesio/io.text:
              text: Select a record
  params:
    recordid:
      type: RECORD
      required: true
      collection: usio/shop.product
