name: product_new
definition:
  # Wires connect to data in collections
  wires:
    product:
      collection: usio/shop.product
      fields:
        usio/shop.name:
        usio/shop.description:
        usio/shop.price:
        usio/shop.slug:
        usio/shop.published:
      init:
        create: true
        query: false
  # Components determine the layout and composition of your view
  components:
    - uesio/io.viewlayout:
        left:
          - usio/shop.nav:
        content:
          - uesio/appkit.layout_detail_split:
              main:
                - uesio/appkit.form_new:
                    wire: product
                    avataricon: sell
                    content:
                      - usio/shop.product_primary_section:
