name: product_detail_content
definition:
  # Wires connect to data in collections
  wires:
    product:
      collection: usio/shop.product
      fields:
        usio/shop.name:
        usio/shop.description:
        usio/shop.image:
        usio/shop.price:
        usio/shop.initials:
        usio/shop.slug:
        usio/shop.published:
        uesio/core.updatedby: {}
        uesio/core.updatedat: {}
        uesio/core.createdby: {}
        uesio/core.createdat: {}
        uesio/core.owner: {}
      conditions:
        - field: uesio/core.id
          valueSource: PARAM
          param: recordid
  # Components determine the layout and composition of your view
  components:
    - uesio/appkit.layout_detail_split:
        main:
          - uesio/appkit.form_detail:
              wire: product
              avataricon: credit_card
              imagefield: usio/shop.image
              initials: ${product:initials}
              extra_actions:
                - uesio/io.button:
                    signals:
                      - signal: route/NAVIGATE
                        path: buy/${slug}
                    text: View Listing
                    icon: visibility
                    iconFill: false
                    uesio.variant: uesio/appkit.secondary
                    uesio.display:
                      - type: mergeValue
                        operator: NOT_EQUALS
                        sourceValue: $Text{$FieldMode{}}
                        value: EDIT
                      - type: wireHasNoChanges
                        wire: product
              content:
                - usio/shop.product_primary_section:
        left:
          - uesio/io.tabs:
              uesio.variant: uesio/appkit.main
              tabs:
                - id: orders
                  label: Orders
                  components:
  params:
    recordid:
      type: RECORD
      required: true
      collection: usio/shop.product
