name: product_detail
definition:
  # Components determine the layout and composition of your view
  components:
    - uesio/io.viewlayout:
        left:
          - usio/pay.nav:
        content:
          - uesio/core.view:
              view: product_detail_content
              uesio.id: detailcontent
              params:
                recordid: $Param{recordid}
  params:
    recordid:
      type: RECORD
      required: true
      collection: usio/core.product
