name: product_new
definition:
  # Wires connect to data in collections
  wires:
    product:
      collection: usio/pay.product
      fields:
        usio/pay.name:
        usio/pay.description:
        usio/pay.price:
        usio/pay.slug:
        usio/pay.published:
      init:
        create: true
        query: false
  # Components determine the layout and composition of your view
  components:
    - uesio/io.viewlayout:
        left:
          - usio/pay.nav:
        content:
          - usio/pay.detail_split:
              main:
                - uesio/io.list:
                    wire: product
                    uesio.id: productList
                    mode: EDIT
                    components:
                      - uesio/io.titlebar:
                          title: New Product
                          subtitle: "${name}"
                          uesio.variant: usio/pay.main
                          actions:
                            - uesio/io.group:
                                components:
                                  - uesio/io.button:
                                      signals:
                                        - signal: wire/SAVE
                                          wires:
                                            - product
                                        - signal: route/NAVIGATE_TO_ASSIGNMENT
                                          collection: usio/pay.product
                                          viewtype: detail
                                          recordid: ${uesio/core.id}
                                      text: Create Product
                                      hotkey: "meta+s"
                                      uesio.variant: usio/pay.primary
                                  - uesio/io.button:
                                      signals:
                                        - signal: wire/RESET
                                          wire: product
                                      text: Reset
                                      uesio.variant: usio/pay.secondary
                          avatar:
                            - uesio/io.text:
                                uesio.variant: uesio/io.icon
                                text: sell
                      - usio/pay.product_primary_section:
