name: product_tile
category: LAYOUT
type: DECLARATIVE
definition:
  - uesio/io.tile:
      uesio.variant: uesio/appkit.item
      content:
        - uesio/io.titlebar:
            uesio.variant: uesio/appkit.item
            title: ${name}
            subtitle: ${description}
            actions:
      avatar:
        - uesio/io.avatar:
            text: ${initials}
            image: $UserFile{image}
      signals:
        - signal: route/NAVIGATE_TO_ASSIGNMENT
          collection: usio/shop.product
          viewtype: detail
          recordid: ${uesio/core.id}
title: Product Tile Component
discoverable: true
description: A product tile
sections:
  - type: HOME
    properties:
  - type: DISPLAY
